### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by gzzen** [mjbrodie/dsci-310-group-16#2]
Below is a list of feedback that you can make use of to improve your project. If anything is unclear, please feel free to ask questions under this issue thread. We are looking forward to see your next milestone!

### Project organization

- [x] (Addressed) Please make sufficient use of Github issues for features, fixes, task tracking, and other project-related communications (-1)

- [x] Please track the progress of the project using [[Github miltstones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones)](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones), and associate this funcationality with issues and pull requests (-2)
- [x] (Addressed) Please make sufficient use of Github project board by associating Github issue cards into the board. The project board should show the current status of the project to the team. (-3)

### Version control workflow

- [x] Please ensure every feature & fix to be operated under a separate branch, and merge into the main branch using pull requests (-1)

### Doucmentation provided for reproducing the report

- [x] (Addressed) Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing) (-1)

- [x] (Addressed) Please clearly specify usage instructions to the point a user could copy and paste them and they would work (-1)
