### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by gzzen** [mjbrodie/dsci-310-group-16#25]
- [x] (Addressed) `load_libraries.R` is not a function (-2)
- [x] (Addressed) Empty file directory inside the RStudio server of docker container. Try adding commands in Dockerfile to copy the files into the container (-1)
- [ ] Tests are not written for the abstracted functions (-25)
