### ISSUE TITLE
Milestone 3 feedback

### ISSUE THREAD

**Issue by gzzen** [mjbrodie/dsci-310-group-16#44]
# Milestone 3
- [x] Please improve the functionality of `Makefile` such that the `make clean` command fully removes the `output` and `data` directory (also, there is no need to keep a "bogus file" in the directory, as this may confuse the viewer who knows nothing about the project structure)  (-2)
- [x] Please track the progress of the project using Github milestones (-1)
- [x] Please ensure every feature & fix to be operated under a separate branch (-1)
- [x] Please include more detailed instruction in the procedure of generating the report, i.e., where to find the analysis output and report, how to use `make clean`, assuming that the viewer knows nothing about the project structure (-2)

---
# Addressment of previous feedback
The parts that appeared on previous milestone feedback, and has been addressed adequately is labelled with `addressed`, and 50% marks are given back.
- #2 (+3)
- #25 (+1.5)
